server.port=8080

spring.datasource.url=jdbc:postgresql://db.wvwystrxgbdzcmeydrxs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Mohan**@0987
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# JWT Secret
jwt.secret=aVeryLongSecretKeyThatIsAtLeast32BytesLongForHS256Algorithm
jwt.expiration=900000
jwt.refreshExpiration=604800000
